// Auto-generated from `Top 500 Document Types Guide.md`.
// Edit the source markdown and regenerate — do not hand-edit.

import Foundation

/// Canonical document taxonomy used to guide the local tagger LLM.
/// 500 document types across 20 categories — covers personal, legal,
/// business, financial, government, medical, academic, technical and
/// specialty domains.
enum DocumentTaxonomy {
    struct DocumentType: Sendable, Hashable {
        let slug: String       // kebab-case identifier
        let name: String       // display name from the guide
        let purpose: String    // short description
    }
    struct Category: Sendable, Hashable {
        let slug: String
        let name: String
        let types: [DocumentType]
    }

    static let categories: [Category] = [
        Category(slug: "personal-identity-documents", name: "Personal & Identity Documents", types: [
            DocumentType(slug: "passport", name: "Passport", purpose: "International travel identity"),
            DocumentType(slug: "birth-certificate", name: "Birth Certificate", purpose: "Proof of birth and citizenship"),
            DocumentType(slug: "national-id-card", name: "National ID Card", purpose: "Government-issued personal identification"),
            DocumentType(slug: "driver-s-license", name: "Driver's License", purpose: "Vehicle operation authorization and ID"),
            DocumentType(slug: "social-security-card", name: "Social Security Card", purpose: "Tax and benefits identification"),
            DocumentType(slug: "marriage-certificate", name: "Marriage Certificate", purpose: "Legal proof of marriage"),
            DocumentType(slug: "divorce-decree", name: "Divorce Decree", purpose: "Legal dissolution of marriage"),
            DocumentType(slug: "death-certificate", name: "Death Certificate", purpose: "Legal proof of death"),
            DocumentType(slug: "adoption-certificate", name: "Adoption Certificate", purpose: "Legal confirmation of adoption"),
            DocumentType(slug: "naturalization-certificate", name: "Naturalization Certificate", purpose: "Proof of citizenship grant"),
            DocumentType(slug: "baptismal-certificate", name: "Baptismal Certificate", purpose: "Religious record of baptism"),
            DocumentType(slug: "confirmation-certificate", name: "Confirmation Certificate", purpose: "Religious rite confirmation record"),
            DocumentType(slug: "genealogy-record", name: "Genealogy Record", purpose: "Family history and lineage documentation"),
            DocumentType(slug: "personal-diary-journal", name: "Personal Diary / Journal", purpose: "Private daily record of events"),
            DocumentType(slug: "letter", name: "Letter (Personal)", purpose: "Private written communication"),
            DocumentType(slug: "greeting-card", name: "Greeting Card", purpose: "Social correspondence document"),
            DocumentType(slug: "autobiography", name: "Autobiography", purpose: "Self-written life narrative"),
            DocumentType(slug: "personal-resume-cv", name: "Personal Resume / CV", purpose: "Employment application summary"),
            DocumentType(slug: "personal-statement", name: "Personal Statement", purpose: "Academic or professional admission essay"),
            DocumentType(slug: "reference-letter", name: "Reference Letter", purpose: "Character or professional endorsement"),
            DocumentType(slug: "cover-letter", name: "Cover Letter", purpose: "Job application introductory letter"),
            DocumentType(slug: "vehicle-title", name: "Vehicle Title", purpose: "Proof of vehicle ownership"),
            DocumentType(slug: "vehicle-registration", name: "Vehicle Registration", purpose: "Proof of vehicle registration with government"),
            DocumentType(slug: "voter-registration-card", name: "Voter Registration Card", purpose: "Eligibility record for voting"),
            DocumentType(slug: "travel-visa", name: "Travel Visa", purpose: "Permission to enter a foreign country"),
        ]),
        Category(slug: "academic-educational-documents", name: "Academic & Educational Documents", types: [
            DocumentType(slug: "academic-transcript", name: "Academic Transcript", purpose: "Record of coursework and grades"),
            DocumentType(slug: "diploma-degree-certificate", name: "Diploma / Degree Certificate", purpose: "Proof of academic achievement"),
            DocumentType(slug: "high-school-diploma", name: "High School Diploma", purpose: "Secondary education completion certificate"),
            DocumentType(slug: "ged-certificate", name: "GED Certificate", purpose: "General education equivalency credential"),
            DocumentType(slug: "professional-certificate", name: "Professional Certificate", purpose: "Completion of vocational/professional training"),
            DocumentType(slug: "syllabus", name: "Syllabus", purpose: "Course outline, schedule, and expectations"),
            DocumentType(slug: "lesson-plan", name: "Lesson Plan", purpose: "Instructional framework for educators"),
            DocumentType(slug: "student-handbook", name: "Student Handbook", purpose: "School rules and expectations"),
            DocumentType(slug: "report-card", name: "Report Card", purpose: "Student academic progress report"),
            DocumentType(slug: "enrollment-form", name: "Enrollment Form", purpose: "Student registration for school/course"),
            DocumentType(slug: "financial-aid-application", name: "Financial Aid Application", purpose: "Request for educational funding"),
            DocumentType(slug: "fafsa-form", name: "FAFSA Form", purpose: "Federal student financial aid application (US)"),
            DocumentType(slug: "college-application", name: "College Application", purpose: "Admissions request to a university"),
            DocumentType(slug: "recommendation-letter", name: "Recommendation Letter", purpose: "Academic endorsement for a student"),
            DocumentType(slug: "scholarship-application", name: "Scholarship Application", purpose: "Request for merit or need-based award"),
            DocumentType(slug: "academic-essay", name: "Academic Essay", purpose: "Argumentative or analytical academic writing"),
            DocumentType(slug: "term-paper", name: "Term Paper", purpose: "Semester-length academic research paper"),
            DocumentType(slug: "research-paper", name: "Research Paper", purpose: "Scholarly contribution to a discipline"),
            DocumentType(slug: "thesis", name: "Thesis", purpose: "Graduate-level original research capstone"),
            DocumentType(slug: "dissertation", name: "Dissertation", purpose: "Doctoral-level original research document"),
            DocumentType(slug: "literature-review", name: "Literature Review", purpose: "Synthesis of existing scholarly research"),
            DocumentType(slug: "annotated-bibliography", name: "Annotated Bibliography", purpose: "Source list with summaries and evaluations"),
            DocumentType(slug: "lab-report", name: "Lab Report", purpose: "Documents experimental procedures and findings"),
            DocumentType(slug: "case-study", name: "Case Study", purpose: "Analysis of a specific real-world instance"),
            DocumentType(slug: "book-report", name: "Book Report", purpose: "Summary and evaluation of a published book"),
        ]),
        Category(slug: "legal-documents-contracts-agreements", name: "Legal Documents — Contracts & Agreements", types: [
            DocumentType(slug: "contract", name: "Contract", purpose: "Core legally binding agreement"),
            DocumentType(slug: "non-disclosure-agreement", name: "Non-Disclosure Agreement (NDA)", purpose: "Protects confidential information"),
            DocumentType(slug: "non-compete-agreement", name: "Non-Compete Agreement", purpose: "Restricts competitive employment post-departure"),
            DocumentType(slug: "non-solicitation-agreement", name: "Non-Solicitation Agreement", purpose: "Restricts poaching clients or employees"),
            DocumentType(slug: "service-agreement", name: "Service Agreement", purpose: "Terms for delivery of professional services"),
            DocumentType(slug: "service-level-agreement", name: "Service Level Agreement (SLA)", purpose: "Defines performance standards for services"),
            DocumentType(slug: "master-services-agreement", name: "Master Services Agreement (MSA)", purpose: "Overarching framework for recurring engagements"),
            DocumentType(slug: "memorandum-of-understanding", name: "Memorandum of Understanding (MOU)", purpose: "Preliminary, non-binding outline of an agreement"),
            DocumentType(slug: "letter-of-intent", name: "Letter of Intent (LOI)", purpose: "Indicates intent to enter a formal transaction"),
            DocumentType(slug: "settlement-agreement", name: "Settlement Agreement", purpose: "Resolves a legal dispute out of court"),
            DocumentType(slug: "arbitration-agreement", name: "Arbitration Agreement", purpose: "Directs disputes to arbitration vs. litigation"),
            DocumentType(slug: "licensing-agreement", name: "Licensing Agreement", purpose: "Grants rights to use IP, property, or software"),
            DocumentType(slug: "franchise-agreement", name: "Franchise Agreement", purpose: "Terms between franchisor and franchisee"),
            DocumentType(slug: "distribution-agreement", name: "Distribution Agreement", purpose: "Terms for distributing products/services"),
            DocumentType(slug: "joint-venture-agreement", name: "Joint Venture Agreement", purpose: "Terms for two parties pursuing a shared venture"),
            DocumentType(slug: "confidentiality-agreement", name: "Confidentiality Agreement", purpose: "General confidentiality obligations"),
            DocumentType(slug: "subscription-agreement", name: "Subscription Agreement", purpose: "Terms for purchasing securities or subscriptions"),
            DocumentType(slug: "assignment-agreement", name: "Assignment Agreement", purpose: "Transfers rights or obligations to another party"),
            DocumentType(slug: "assumption-agreement", name: "Assumption Agreement", purpose: "One party assumes another's obligations"),
            DocumentType(slug: "indemnification-agreement", name: "Indemnification Agreement", purpose: "One party holds another harmless from losses"),
            DocumentType(slug: "release-agreement", name: "Release Agreement", purpose: "Releases claims between parties"),
            DocumentType(slug: "waiver", name: "Waiver", purpose: "Voluntarily surrenders a legal right or claim"),
            DocumentType(slug: "covenant", name: "Covenant", purpose: "Formal binding agreement or pledge"),
            DocumentType(slug: "lease-agreement", name: "Lease Agreement", purpose: "Real estate or equipment rental terms"),
            DocumentType(slug: "sublease-agreement", name: "Sublease Agreement", purpose: "Renter re-leases space to another party"),
        ]),
        Category(slug: "legal-documents-instruments-court-filings", name: "Legal Documents — Instruments & Court Filings", types: [
            DocumentType(slug: "deed", name: "Deed", purpose: "Transfers real estate ownership"),
            DocumentType(slug: "warranty-deed", name: "Warranty Deed", purpose: "Deed guaranteeing clear title"),
            DocumentType(slug: "quitclaim-deed", name: "Quitclaim Deed", purpose: "Transfers whatever interest grantor holds"),
            DocumentType(slug: "deed-of-trust", name: "Deed of Trust", purpose: "Secures a loan against real property"),
            DocumentType(slug: "mortgage-document", name: "Mortgage Document", purpose: "Real estate loan security instrument"),
            DocumentType(slug: "will-last-testament", name: "Will / Last Testament", purpose: "Directs asset distribution after death"),
            DocumentType(slug: "codicil", name: "Codicil", purpose: "Amendment or supplement to a will"),
            DocumentType(slug: "living-will-advance-directive", name: "Living Will / Advance Directive", purpose: "Specifies healthcare wishes while incapacitated"),
            DocumentType(slug: "trust-agreement", name: "Trust Agreement", purpose: "Holds and manages assets for beneficiaries"),
            DocumentType(slug: "power-of-attorney", name: "Power of Attorney (POA)", purpose: "Delegates legal authority to another person"),
            DocumentType(slug: "healthcare-power-of-attorney", name: "Healthcare Power of Attorney", purpose: "POA specific to medical decisions"),
            DocumentType(slug: "affidavit", name: "Affidavit", purpose: "Sworn written statement of facts"),
            DocumentType(slug: "deposition", name: "Deposition", purpose: "Sworn out-of-court oral testimony, transcribed"),
            DocumentType(slug: "complaint-petition", name: "Complaint / Petition", purpose: "Initiates a civil legal proceeding"),
            DocumentType(slug: "summons", name: "Summons", purpose: "Notifies a defendant of legal action"),
            DocumentType(slug: "subpoena", name: "Subpoena", purpose: "Compels testimony or production of documents"),
            DocumentType(slug: "subpoena-duces-tecum", name: "Subpoena Duces Tecum", purpose: "Compels production of specific documents"),
            DocumentType(slug: "motion", name: "Motion", purpose: "Formal request to the court for an order"),
            DocumentType(slug: "brief", name: "Brief", purpose: "Written legal argument submitted to court"),
            DocumentType(slug: "court-order", name: "Court Order", purpose: "Judicial directive binding on the parties"),
            DocumentType(slug: "judgment", name: "Judgment", purpose: "Court's final decision resolving a dispute"),
            DocumentType(slug: "injunction", name: "Injunction", purpose: "Court order requiring or prohibiting an action"),
            DocumentType(slug: "warrant", name: "Warrant", purpose: "Authorization for arrest or search"),
            DocumentType(slug: "indictment", name: "Indictment", purpose: "Formal criminal accusation by a grand jury"),
            DocumentType(slug: "plea-agreement", name: "Plea Agreement", purpose: "Negotiated resolution in a criminal case"),
        ]),
        Category(slug: "business-corporate-documents", name: "Business & Corporate Documents", types: [
            DocumentType(slug: "business-plan", name: "Business Plan", purpose: "Strategic roadmap for a business"),
            DocumentType(slug: "articles-of-incorporation", name: "Articles of Incorporation", purpose: "Formally establishes a corporation"),
            DocumentType(slug: "articles-of-organization", name: "Articles of Organization", purpose: "Establishes an LLC with the state"),
            DocumentType(slug: "llc-operating-agreement", name: "LLC Operating Agreement", purpose: "Internal rules for LLC management"),
            DocumentType(slug: "corporate-bylaws", name: "Corporate Bylaws", purpose: "Internal governance rules for a corporation"),
            DocumentType(slug: "partnership-agreement", name: "Partnership Agreement", purpose: "Defines roles, duties, and profit sharing"),
            DocumentType(slug: "shareholder-agreement", name: "Shareholder Agreement", purpose: "Rights and obligations of shareholders"),
            DocumentType(slug: "board-resolution", name: "Board Resolution", purpose: "Formal record of board decision"),
            DocumentType(slug: "meeting-minutes", name: "Meeting Minutes", purpose: "Official record of meeting proceedings"),
            DocumentType(slug: "corporate-charter", name: "Corporate Charter", purpose: "Foundational document of a corporation"),
            DocumentType(slug: "annual-report", name: "Annual Report", purpose: "Yearly overview of corporate performance"),
            DocumentType(slug: "business-report", name: "Business Report", purpose: "Operational or strategic analysis"),
            DocumentType(slug: "swot-analysis", name: "SWOT Analysis", purpose: "Strengths, weaknesses, opportunities, threats"),
            DocumentType(slug: "executive-summary", name: "Executive Summary", purpose: "High-level summary of a plan or proposal"),
            DocumentType(slug: "feasibility-study", name: "Feasibility Study", purpose: "Assessment of whether a project is viable"),
            DocumentType(slug: "business-proposal", name: "Business Proposal", purpose: "Offer to provide products or services"),
            DocumentType(slug: "request-for-proposal", name: "Request for Proposal (RFP)", purpose: "Solicitation for bids from vendors"),
            DocumentType(slug: "request-for-quotation", name: "Request for Quotation (RFQ)", purpose: "Solicitation for price quotes"),
            DocumentType(slug: "statement-of-work", name: "Statement of Work (SOW)", purpose: "Describes work scope, deliverables, timeline"),
            DocumentType(slug: "project-charter", name: "Project Charter", purpose: "Formally authorizes and scopes a project"),
            DocumentType(slug: "project-plan", name: "Project Plan", purpose: "Roadmap of tasks, timelines, and resources"),
            DocumentType(slug: "project-status-report", name: "Project Status Report", purpose: "Progress update on active project"),
            DocumentType(slug: "change-order", name: "Change Order", purpose: "Documents modification to original agreement"),
            DocumentType(slug: "business-continuity-plan", name: "Business Continuity Plan", purpose: "Procedures for maintaining operations during crisis"),
            DocumentType(slug: "disaster-recovery-plan", name: "Disaster Recovery Plan", purpose: "Steps to restore systems after disruption"),
        ]),
        Category(slug: "human-resources-documents", name: "Human Resources Documents", types: [
            DocumentType(slug: "job-description", name: "Job Description", purpose: "Outlines role responsibilities and qualifications"),
            DocumentType(slug: "job-application-form", name: "Job Application Form", purpose: "Collects candidate details for consideration"),
            DocumentType(slug: "offer-letter", name: "Offer Letter", purpose: "Extends and formalizes employment offer"),
            DocumentType(slug: "employment-contract", name: "Employment Contract", purpose: "Binding agreement of employment terms"),
            DocumentType(slug: "independent-contractor-agreement", name: "Independent Contractor Agreement", purpose: "Terms for freelance or contract work"),
            DocumentType(slug: "i-9-form", name: "I-9 Form", purpose: "Work eligibility verification (US)"),
            DocumentType(slug: "w-4-form", name: "W-4 Form", purpose: "Tax withholding election form (US)"),
            DocumentType(slug: "w-2-form", name: "W-2 Form", purpose: "Annual wage and tax statement to employee"),
            DocumentType(slug: "employee-handbook", name: "Employee Handbook", purpose: "Company policies, procedures, and culture"),
            DocumentType(slug: "onboarding-checklist", name: "Onboarding Checklist", purpose: "Steps and forms for new employee orientation"),
            DocumentType(slug: "organization-chart", name: "Organization Chart", purpose: "Visual map of company reporting structure"),
            DocumentType(slug: "staffing-plan", name: "Staffing Plan", purpose: "Workforce planning document"),
            DocumentType(slug: "performance-review", name: "Performance Review", purpose: "Formal employee evaluation record"),
            DocumentType(slug: "performance-improvement-plan", name: "Performance Improvement Plan (PIP)", purpose: "Structured plan to address performance gaps"),
            DocumentType(slug: "disciplinary-notice", name: "Disciplinary Notice", purpose: "Formal warning or reprimand"),
            DocumentType(slug: "termination-letter", name: "Termination Letter", purpose: "Official notice of employment end"),
            DocumentType(slug: "resignation-letter", name: "Resignation Letter", purpose: "Employee's formal notice of departure"),
            DocumentType(slug: "exit-interview-form", name: "Exit Interview Form", purpose: "Captures departing employee's feedback"),
            DocumentType(slug: "severance-agreement", name: "Severance Agreement", purpose: "Terms of separation package"),
            DocumentType(slug: "non-solicitation-clause-document", name: "Non-Solicitation Clause Document", purpose: "HR-specific post-employment restriction"),
            DocumentType(slug: "benefits-enrollment-form", name: "Benefits Enrollment Form", purpose: "Election of health and retirement benefits"),
            DocumentType(slug: "cobra-notice", name: "COBRA Notice", purpose: "Health insurance continuation notification"),
            DocumentType(slug: "fmla-request-form", name: "FMLA Request Form", purpose: "Family/medical leave application (US)"),
            DocumentType(slug: "workplace-incident-report", name: "Workplace Incident Report", purpose: "Documents on-the-job accident or injury"),
            DocumentType(slug: "training-certificate", name: "Training Certificate", purpose: "Confirms completion of a training program"),
        ]),
        Category(slug: "financial-accounting-documents", name: "Financial & Accounting Documents", types: [
            DocumentType(slug: "invoice", name: "Invoice", purpose: "Request for payment for goods or services"),
            DocumentType(slug: "receipt", name: "Receipt", purpose: "Proof of payment received"),
            DocumentType(slug: "purchase-order", name: "Purchase Order", purpose: "Authorization to buy goods/services"),
            DocumentType(slug: "quotation-quote", name: "Quotation / Quote", purpose: "Formal pricing offer to a customer"),
            DocumentType(slug: "sales-order", name: "Sales Order", purpose: "Confirms a customer order"),
            DocumentType(slug: "credit-note", name: "Credit Note", purpose: "Reduces amount owed to seller"),
            DocumentType(slug: "debit-note", name: "Debit Note", purpose: "Increases amount owed to seller"),
            DocumentType(slug: "remittance-advice", name: "Remittance Advice", purpose: "Notification accompanying a payment"),
            DocumentType(slug: "bank-statement", name: "Bank Statement", purpose: "Record of account transactions"),
            DocumentType(slug: "bank-reconciliation", name: "Bank Reconciliation", purpose: "Matches company records to bank statement"),
            DocumentType(slug: "expense-report", name: "Expense Report", purpose: "Documents and requests reimbursement for expenses"),
            DocumentType(slug: "petty-cash-voucher", name: "Petty Cash Voucher", purpose: "Records small cash disbursements"),
            DocumentType(slug: "income-statement", name: "Income Statement (P&L)", purpose: "Revenue and expense summary"),
            DocumentType(slug: "balance-sheet", name: "Balance Sheet", purpose: "Assets, liabilities, and equity snapshot"),
            DocumentType(slug: "cash-flow-statement", name: "Cash Flow Statement", purpose: "Tracks cash inflows and outflows"),
            DocumentType(slug: "statement-of-shareholders-equity", name: "Statement of Shareholders' Equity", purpose: "Shows changes in ownership interest"),
            DocumentType(slug: "trial-balance", name: "Trial Balance", purpose: "Lists all ledger accounts and balances"),
            DocumentType(slug: "general-ledger", name: "General Ledger", purpose: "Master record of all financial transactions"),
            DocumentType(slug: "journal-entry", name: "Journal Entry", purpose: "Records a specific financial transaction"),
            DocumentType(slug: "chart-of-accounts", name: "Chart of Accounts", purpose: "Organized index of all financial accounts"),
            DocumentType(slug: "budget", name: "Budget", purpose: "Financial plan for a period"),
            DocumentType(slug: "variance-report", name: "Variance Report", purpose: "Compares actual vs. budgeted figures"),
            DocumentType(slug: "payroll-register", name: "Payroll Register", purpose: "Complete payroll record for a pay period"),
            DocumentType(slug: "pay-stub-payslip", name: "Pay Stub / Payslip", purpose: "Individual employee earnings statement"),
            DocumentType(slug: "tax-return", name: "Tax Return (Individual)", purpose: "Annual personal income tax filing (e.g., Form 1040)"),
            DocumentType(slug: "corporate-tax-return", name: "Corporate Tax Return", purpose: "Annual business income tax filing"),
            DocumentType(slug: "sales-tax-return", name: "Sales Tax Return", purpose: "Periodic state sales tax filing"),
            DocumentType(slug: "form-1099", name: "Form 1099", purpose: "Reports non-employee compensation"),
            DocumentType(slug: "audit-report", name: "Audit Report", purpose: "Independent financial review and opinion"),
            DocumentType(slug: "internal-audit-report", name: "Internal Audit Report", purpose: "Internal controls and compliance assessment"),
            DocumentType(slug: "financial-projection", name: "Financial Projection", purpose: "Forward-looking financial estimate"),
            DocumentType(slug: "pro-forma-statement", name: "Pro Forma Statement", purpose: "Hypothetical financial scenario"),
            DocumentType(slug: "fixed-asset-register", name: "Fixed Asset Register", purpose: "Tracks company's long-term assets"),
            DocumentType(slug: "depreciation-schedule", name: "Depreciation Schedule", purpose: "Schedules asset value reduction over time"),
            DocumentType(slug: "accounts-receivable-aging-report", name: "Accounts Receivable Aging Report", purpose: "Tracks outstanding customer invoices"),
            DocumentType(slug: "accounts-payable-schedule", name: "Accounts Payable Schedule", purpose: "Tracks outstanding vendor invoices"),
            DocumentType(slug: "loan-agreement", name: "Loan Agreement", purpose: "Terms of a debt obligation"),
            DocumentType(slug: "promissory-note", name: "Promissory Note", purpose: "Written repayment promise for a loan"),
            DocumentType(slug: "line-of-credit-agreement", name: "Line of Credit Agreement", purpose: "Terms for revolving credit facility"),
            DocumentType(slug: "personal-financial-statement", name: "Personal Financial Statement", purpose: "Individual's assets and liabilities summary"),
        ]),
        Category(slug: "real-estate-property-documents", name: "Real Estate & Property Documents", types: [
            DocumentType(slug: "purchase-agreement", name: "Purchase Agreement", purpose: "Terms and conditions of a property sale"),
            DocumentType(slug: "earnest-money-contract", name: "Earnest Money Contract", purpose: "Buyer-seller agreement before closing"),
            DocumentType(slug: "closing-disclosure", name: "Closing Disclosure", purpose: "Final financial summary of a real estate transaction"),
            DocumentType(slug: "hud-1-settlement-statement", name: "HUD-1 Settlement Statement", purpose: "Itemizes all transaction costs at closing"),
            DocumentType(slug: "title-report", name: "Title Report", purpose: "Discloses title condition and any liens"),
            DocumentType(slug: "title-insurance-policy", name: "Title Insurance Policy", purpose: "Insures against title defects"),
            DocumentType(slug: "survey-plat", name: "Survey / Plat", purpose: "Maps physical boundaries of a property"),
            DocumentType(slug: "legal-description", name: "Legal Description", purpose: "Written boundary description of real property"),
            DocumentType(slug: "hoa-documents", name: "HOA Documents", purpose: "Rules, bylaws, and fees for homeowner associations"),
            DocumentType(slug: "property-disclosure", name: "Property Disclosure", purpose: "Seller disclosure of known defects or hazards"),
            DocumentType(slug: "appraisal-report", name: "Appraisal Report", purpose: "Professional estimate of property value"),
            DocumentType(slug: "home-inspection-report", name: "Home Inspection Report", purpose: "Assessment of property condition"),
            DocumentType(slug: "zoning-certificate", name: "Zoning Certificate", purpose: "Confirms permitted land use"),
            DocumentType(slug: "building-permit", name: "Building Permit", purpose: "Authorization to construct or renovate"),
            DocumentType(slug: "certificate-of-occupancy", name: "Certificate of Occupancy", purpose: "Confirms a building meets safety standards"),
            DocumentType(slug: "easement-agreement", name: "Easement Agreement", purpose: "Grants right of use over another's property"),
            DocumentType(slug: "lien", name: "Lien", purpose: "Claim on property as security for a debt"),
            DocumentType(slug: "mechanic-s-lien", name: "Mechanic's Lien", purpose: "Filed by contractors for unpaid work"),
            DocumentType(slug: "lis-pendens", name: "Lis Pendens", purpose: "Notice of pending lawsuit affecting property"),
            DocumentType(slug: "foreclosure-notice", name: "Foreclosure Notice", purpose: "Legal notice of foreclosure proceedings"),
            DocumentType(slug: "lease-agreement-real-estate", name: "Lease Agreement (Real Estate)", purpose: "Terms for renting real property"),
            DocumentType(slug: "commercial-lease", name: "Commercial Lease", purpose: "Terms for renting commercial space"),
            DocumentType(slug: "rent-roll", name: "Rent Roll", purpose: "Summary of rental income from a property"),
            DocumentType(slug: "tenant-application", name: "Tenant Application", purpose: "Rental candidacy information form"),
            DocumentType(slug: "property-management-agreement", name: "Property Management Agreement", purpose: "Engages a manager for a property"),
        ]),
        Category(slug: "insurance-documents", name: "Insurance Documents", types: [
            DocumentType(slug: "insurance-policy", name: "Insurance Policy", purpose: "Comprehensive coverage terms and conditions"),
            DocumentType(slug: "certificate-of-insurance", name: "Certificate of Insurance", purpose: "Evidence of insurance coverage in force"),
            DocumentType(slug: "declaration-page", name: "Declaration Page", purpose: "Summary of policy specifics (insured, coverage, dates)"),
            DocumentType(slug: "insurance-claim-form", name: "Insurance Claim Form", purpose: "Formal request for insurance payout"),
            DocumentType(slug: "proof-of-loss-statement", name: "Proof of Loss Statement", purpose: "Sworn statement of loss for a claim"),
            DocumentType(slug: "explanation-of-benefits", name: "Explanation of Benefits (EOB)", purpose: "Details what insurer paid and what patient owes"),
            DocumentType(slug: "health-insurance-id-card", name: "Health Insurance ID Card", purpose: "Member identification for healthcare use"),
            DocumentType(slug: "summary-of-benefits-and-coverage", name: "Summary of Benefits and Coverage (SBC)", purpose: "Plain-language overview of health plan benefits"),
            DocumentType(slug: "summary-plan-description", name: "Summary Plan Description (SPD)", purpose: "Employer-provided plan explanation"),
            DocumentType(slug: "renewal-notice", name: "Renewal Notice", purpose: "Notification of upcoming policy renewal"),
            DocumentType(slug: "cancellation-notice", name: "Cancellation Notice", purpose: "Notification of policy cancellation"),
            DocumentType(slug: "endorsement-rider", name: "Endorsement / Rider", purpose: "Modification or addition to existing policy"),
            DocumentType(slug: "umbrella-policy", name: "Umbrella Policy", purpose: "Excess liability coverage document"),
            DocumentType(slug: "binder", name: "Binder", purpose: "Temporary insurance coverage document"),
            DocumentType(slug: "subrogation-agreement", name: "Subrogation Agreement", purpose: "Insurer's right to recover from third party"),
        ]),
        Category(slug: "government-regulatory-documents", name: "Government & Regulatory Documents", types: [
            DocumentType(slug: "constitution", name: "Constitution", purpose: "Supreme law of a nation or organization"),
            DocumentType(slug: "legislation-statute", name: "Legislation / Statute", purpose: "Enacted law passed by a legislative body"),
            DocumentType(slug: "regulation", name: "Regulation", purpose: "Rule issued by a regulatory agency"),
            DocumentType(slug: "executive-order", name: "Executive Order", purpose: "Presidential/gubernatorial directive"),
            DocumentType(slug: "proclamation", name: "Proclamation", purpose: "Official formal announcement by authority"),
            DocumentType(slug: "bill", name: "Bill (Congressional)", purpose: "Proposed legislation before a vote"),
            DocumentType(slug: "ordinance", name: "Ordinance", purpose: "Local government law or regulation"),
            DocumentType(slug: "treaty", name: "Treaty", purpose: "Formal agreement between nations"),
            DocumentType(slug: "white-paper", name: "White Paper", purpose: "Government or policy analysis document"),
            DocumentType(slug: "green-paper", name: "Green Paper", purpose: "Consultative discussion document for policy"),
            DocumentType(slug: "policy-paper", name: "Policy Paper", purpose: "Formal statement of government policy"),
            DocumentType(slug: "government-report", name: "Government Report", purpose: "Official analysis or study by an agency"),
            DocumentType(slug: "census-data-report", name: "Census Data Report", purpose: "Population and demographic statistics"),
            DocumentType(slug: "environmental-impact-statement", name: "Environmental Impact Statement", purpose: "Assessment of a project's environmental effects"),
            DocumentType(slug: "foia-request", name: "FOIA Request", purpose: "Freedom of Information Act records request"),
            DocumentType(slug: "business-license", name: "Business License", purpose: "Government authorization to operate"),
            DocumentType(slug: "professional-license", name: "Professional License", purpose: "Authorization to practice a regulated profession"),
            DocumentType(slug: "dba-filing", name: "DBA Filing", purpose: "\"Doing Business As\" trade name registration"),
            DocumentType(slug: "ein-application", name: "EIN Application (SS-4)", purpose: "Business tax identification request"),
            DocumentType(slug: "certificate-of-incorporation", name: "Certificate of Incorporation (State)", purpose: "State confirmation of entity formation"),
            DocumentType(slug: "certificate-of-good-standing", name: "Certificate of Good Standing", purpose: "Confirms entity is compliant with state requirements"),
            DocumentType(slug: "annual-report-state-filing", name: "Annual Report (State Filing)", purpose: "Periodic corporate compliance filing"),
            DocumentType(slug: "tax-lien-notice", name: "Tax Lien Notice", purpose: "Government claim for unpaid taxes"),
            DocumentType(slug: "audit-notification-letter", name: "Audit Notification Letter", purpose: "Notice of government tax audit"),
            DocumentType(slug: "customs-declaration-form", name: "Customs Declaration Form", purpose: "Goods declaration at international borders"),
        ]),
        Category(slug: "medical-healthcare-documents", name: "Medical & Healthcare Documents", types: [
            DocumentType(slug: "patient-history-physical", name: "Patient History & Physical (H&P)", purpose: "Comprehensive record of health history and exam"),
            DocumentType(slug: "progress-note", name: "Progress Note", purpose: "Ongoing clinical update on a patient's condition"),
            DocumentType(slug: "soap-note", name: "SOAP Note", purpose: "Structured clinical note (Subjective, Objective, Assessment, Plan)"),
            DocumentType(slug: "discharge-summary", name: "Discharge Summary", purpose: "Documentation of inpatient episode and follow-up plan"),
            DocumentType(slug: "referral-letter", name: "Referral Letter", purpose: "Physician's recommendation to a specialist"),
            DocumentType(slug: "prescription", name: "Prescription", purpose: "Authorized medication order"),
            DocumentType(slug: "medication-administration-record", name: "Medication Administration Record (MAR)", purpose: "Log of administered medications"),
            DocumentType(slug: "lab-report-medical", name: "Lab Report (Medical)", purpose: "Results of diagnostic laboratory tests"),
            DocumentType(slug: "radiology-report", name: "Radiology Report", purpose: "Interpretation of imaging (X-ray, MRI, CT)"),
            DocumentType(slug: "pathology-report", name: "Pathology Report", purpose: "Tissue specimen analysis results"),
            DocumentType(slug: "biopsy-report", name: "Biopsy Report", purpose: "Results of tissue biopsy examination"),
            DocumentType(slug: "operative-report", name: "Operative Report", purpose: "Detailed account of a surgical procedure"),
            DocumentType(slug: "anesthesia-record", name: "Anesthesia Record", purpose: "Documents anesthesia during surgery"),
            DocumentType(slug: "nursing-assessment", name: "Nursing Assessment", purpose: "Nurse's documented evaluation of a patient"),
            DocumentType(slug: "informed-consent-form", name: "Informed Consent Form", purpose: "Patient authorization for treatment/procedure"),
            DocumentType(slug: "hipaa-authorization-form", name: "HIPAA Authorization Form", purpose: "Permission to use/disclose health information"),
            DocumentType(slug: "advance-directive", name: "Advance Directive", purpose: "Healthcare wishes when unable to communicate"),
            DocumentType(slug: "do-not-resuscitate-order", name: "Do Not Resuscitate Order (DNR)", purpose: "Formal medical order to forgo resuscitation"),
            DocumentType(slug: "mental-status-examination", name: "Mental Status Examination", purpose: "Structured assessment of cognitive and psychiatric status"),
            DocumentType(slug: "psychiatric-evaluation", name: "Psychiatric Evaluation", purpose: "Comprehensive mental health assessment"),
            DocumentType(slug: "patient-information-leaflet", name: "Patient Information Leaflet (PIL)", purpose: "Written medicine instructions for patients"),
            DocumentType(slug: "immunization-record", name: "Immunization Record", purpose: "Log of vaccines received"),
            DocumentType(slug: "certificate-of-medical-necessity", name: "Certificate of Medical Necessity", purpose: "Documents medical justification for treatment"),
            DocumentType(slug: "autopsy-report", name: "Autopsy Report", purpose: "Post-mortem examination findings"),
            DocumentType(slug: "medical-examiner-s-certificate", name: "Medical Examiner's Certificate", purpose: "Official documentation of cause of death"),
            DocumentType(slug: "eeg-report", name: "EEG Report", purpose: "Brainwave activity test results"),
            DocumentType(slug: "emg-nerve-conduction-report", name: "EMG / Nerve Conduction Report", purpose: "Neuromuscular function test results"),
            DocumentType(slug: "independent-medical-examination", name: "Independent Medical Examination (IME)", purpose: "Neutral third-party medical evaluation"),
            DocumentType(slug: "radiation-oncology-report", name: "Radiation Oncology Report", purpose: "Cancer radiation treatment documentation"),
            DocumentType(slug: "home-health-care-plan", name: "Home Health Care Plan", purpose: "Instructions for care delivered at home"),
        ]),
        Category(slug: "shipping-logistics-trade-documents", name: "Shipping, Logistics & Trade Documents", types: [
            DocumentType(slug: "bill-of-lading", name: "Bill of Lading (BOL)", purpose: "Contract between shipper and carrier; title document"),
            DocumentType(slug: "air-waybill", name: "Air Waybill", purpose: "Shipping receipt for air cargo"),
            DocumentType(slug: "sea-waybill", name: "Sea Waybill", purpose: "Non-negotiable cargo receipt for ocean freight"),
            DocumentType(slug: "rail-waybill", name: "Rail Waybill", purpose: "Freight contract for rail transport"),
            DocumentType(slug: "packing-list", name: "Packing List", purpose: "Itemized contents of a shipment"),
            DocumentType(slug: "commercial-invoice", name: "Commercial Invoice", purpose: "Proof of sale for customs purposes"),
            DocumentType(slug: "certificate-of-origin", name: "Certificate of Origin", purpose: "Certifies country of manufacture"),
            DocumentType(slug: "export-customs-declaration", name: "Export Customs Declaration", purpose: "Government-required export form"),
            DocumentType(slug: "import-customs-declaration", name: "Import Customs Declaration", purpose: "Government-required import clearance form"),
            DocumentType(slug: "letter-of-credit", name: "Letter of Credit", purpose: "Bank-issued trade payment guarantee"),
            DocumentType(slug: "shipping-guarantee", name: "Shipping Guarantee", purpose: "Bank guarantee for cargo release before documents arrive"),
            DocumentType(slug: "delivery-order", name: "Delivery Order", purpose: "Authorizes release of cargo to a party"),
            DocumentType(slug: "dock-receipt", name: "Dock Receipt", purpose: "Confirms cargo receipt at port"),
            DocumentType(slug: "arrival-notice", name: "Arrival Notice", purpose: "Notifies consignee cargo has arrived"),
            DocumentType(slug: "importer-security-filing", name: "Importer Security Filing (ISF)", purpose: "Pre-shipment data filing with US Customs"),
            DocumentType(slug: "phytosanitary-certificate", name: "Phytosanitary Certificate", purpose: "Certifies plant products are pest-free"),
            DocumentType(slug: "dangerous-goods-declaration", name: "Dangerous Goods Declaration", purpose: "Required for hazardous material shipment"),
            DocumentType(slug: "fumigation-certificate", name: "Fumigation Certificate", purpose: "Certifies cargo was fumigated"),
            DocumentType(slug: "inspection-certificate", name: "Inspection Certificate", purpose: "Third-party verification of goods quality"),
            DocumentType(slug: "pro-forma-invoice", name: "Pro Forma Invoice", purpose: "Preliminary invoice for customs/quotation"),
            DocumentType(slug: "freight-invoice", name: "Freight Invoice", purpose: "Carrier's charge document for transportation"),
            DocumentType(slug: "warehouse-receipt", name: "Warehouse Receipt", purpose: "Confirms goods are stored in a warehouse"),
            DocumentType(slug: "consignment-note", name: "Consignment Note", purpose: "Accompanies goods in transit as identification"),
            DocumentType(slug: "export-license", name: "Export License", purpose: "Government authorization to export controlled goods"),
            DocumentType(slug: "import-permit", name: "Import Permit", purpose: "Government authorization to import specific goods"),
        ]),
        Category(slug: "technical-engineering-documents", name: "Technical & Engineering Documents", types: [
            DocumentType(slug: "technical-specification", name: "Technical Specification", purpose: "Defines system or product requirements"),
            DocumentType(slug: "design-specification", name: "Design Specification", purpose: "Details parameters of a design (voltages, materials, etc.)"),
            DocumentType(slug: "engineering-drawing", name: "Engineering Drawing (Part Drawing)", purpose: "Single-part manufacturing blueprint"),
            DocumentType(slug: "assembly-drawing", name: "Assembly Drawing", purpose: "Shows how components fit together"),
            DocumentType(slug: "schematic-diagram", name: "Schematic Diagram", purpose: "Circuit or system connection visual"),
            DocumentType(slug: "bill-of-materials", name: "Bill of Materials (BOM)", purpose: "List of all components for a product"),
            DocumentType(slug: "parts-list", name: "Parts List", purpose: "Document listing parts in an assembly"),
            DocumentType(slug: "calculation-sheet", name: "Calculation Sheet", purpose: "Mathematical analysis supporting design decisions"),
            DocumentType(slug: "test-plan", name: "Test Plan", purpose: "Procedures for verifying system function"),
            DocumentType(slug: "test-report", name: "Test Report", purpose: "Documented outcomes of testing activities"),
            DocumentType(slug: "failure-mode-and-effects-analysis", name: "Failure Mode and Effects Analysis (FMEA)", purpose: "Risk analysis of potential failure modes"),
            DocumentType(slug: "environmental-safety-assessment", name: "Environmental / Safety Assessment", purpose: "Evaluates environmental or safety risks"),
            DocumentType(slug: "inspection-checklist", name: "Inspection Checklist", purpose: "Verification form for quality standards"),
            DocumentType(slug: "work-instruction", name: "Work Instruction", purpose: "Step-by-step guidance for a process"),
            DocumentType(slug: "assembly-instruction", name: "Assembly Instruction", purpose: "Guide for assembling a product"),
            DocumentType(slug: "maintenance-manual", name: "Maintenance Manual", purpose: "Instructions for maintaining equipment"),
            DocumentType(slug: "calibration-record", name: "Calibration Record", purpose: "Documents instrument calibration status"),
            DocumentType(slug: "change-request", name: "Change Request", purpose: "Formal request to alter a design or system"),
            DocumentType(slug: "engineering-change-notice", name: "Engineering Change Notice (ECN)", purpose: "Official notification of a design change"),
            DocumentType(slug: "requirement-specification", name: "Requirement Specification", purpose: "States what a system must do (functional/non-functional)"),
            DocumentType(slug: "document-list-index", name: "Document List / Index", purpose: "Inventory of all relevant documents for a project"),
            DocumentType(slug: "product-definition-document", name: "Product Definition Document", purpose: "Text-based companion to a drawing"),
            DocumentType(slug: "part-definition-document", name: "Part Definition Document", purpose: "Specifies material or property requirements"),
            DocumentType(slug: "interface-control-document", name: "Interface Control Document (ICD)", purpose: "Defines how systems interface with each other"),
            DocumentType(slug: "safety-case", name: "Safety Case", purpose: "Structured argument that a system is safe"),
        ]),
        Category(slug: "software-it-documents", name: "Software & IT Documents", types: [
            DocumentType(slug: "software-requirements-specification", name: "Software Requirements Specification (SRS)", purpose: "Defines what software must do"),
            DocumentType(slug: "system-architecture-document", name: "System Architecture Document", purpose: "Describes overall system design"),
            DocumentType(slug: "api-documentation", name: "API Documentation", purpose: "Developer reference for software interfaces"),
            DocumentType(slug: "sdk-manual", name: "SDK Manual", purpose: "Guide for using a software development kit"),
            DocumentType(slug: "user-manual-user-guide", name: "User Manual / User Guide", purpose: "End-user instructions for a product"),
            DocumentType(slug: "quick-start-guide", name: "Quick Start Guide", purpose: "Abbreviated getting-started instructions"),
            DocumentType(slug: "release-notes", name: "Release Notes", purpose: "Changelog for software versions"),
            DocumentType(slug: "readme-file", name: "README File", purpose: "Introductory documentation for software projects"),
            DocumentType(slug: "process-documentation", name: "Process Documentation", purpose: "Records software development and maintenance"),
            DocumentType(slug: "development-plan", name: "Development Plan", purpose: "Roadmap for software project completion"),
            DocumentType(slug: "technical-roadmap", name: "Technical Roadmap", purpose: "Long-term product or system direction"),
            DocumentType(slug: "product-backlog", name: "Product Backlog", purpose: "Prioritized list of development tasks"),
            DocumentType(slug: "sprint-plan", name: "Sprint Plan", purpose: "Work schedule for an agile sprint"),
            DocumentType(slug: "bug-report", name: "Bug Report", purpose: "Documents a software defect"),
            DocumentType(slug: "incident-report", name: "Incident Report (IT)", purpose: "Documents a system outage or security event"),
            DocumentType(slug: "runbook", name: "Runbook", purpose: "Step-by-step IT operations guide"),
            DocumentType(slug: "disaster-recovery-plan-it", name: "Disaster Recovery Plan (IT)", purpose: "IT-specific data and system recovery document"),
            DocumentType(slug: "security-policy", name: "Security Policy", purpose: "Information security rules and standards"),
            DocumentType(slug: "privacy-policy", name: "Privacy Policy", purpose: "How personal data is collected and used"),
            DocumentType(slug: "terms-of-service", name: "Terms of Service", purpose: "Rules governing use of a digital product"),
            DocumentType(slug: "data-dictionary", name: "Data Dictionary", purpose: "Defines fields and data within a system"),
            DocumentType(slug: "network-diagram", name: "Network Diagram", purpose: "Visual map of IT infrastructure"),
            DocumentType(slug: "configuration-management-plan", name: "Configuration Management Plan", purpose: "Controls changes to IT system configurations"),
            DocumentType(slug: "penetration-test-report", name: "Penetration Test Report", purpose: "Documents ethical hacking findings"),
            DocumentType(slug: "compliance-report", name: "Compliance Report (SOC 2, ISO)", purpose: "Certifies adherence to security standards"),
        ]),
        Category(slug: "research-scientific-documents", name: "Research & Scientific Documents", types: [
            DocumentType(slug: "journal-article", name: "Journal Article", purpose: "Peer-reviewed scientific contribution"),
            DocumentType(slug: "review-article", name: "Review Article", purpose: "Synthesizes existing research in a field"),
            DocumentType(slug: "systematic-review", name: "Systematic Review", purpose: "Methodical review using defined search criteria"),
            DocumentType(slug: "meta-analysis", name: "Meta-Analysis", purpose: "Statistical synthesis of multiple studies"),
            DocumentType(slug: "experimental-research-paper", name: "Experimental Research Paper", purpose: "Reports controlled experiment results"),
            DocumentType(slug: "survey-based-research-paper", name: "Survey-Based Research Paper", purpose: "Reports findings from survey methodology"),
            DocumentType(slug: "qualitative-research-paper", name: "Qualitative Research Paper", purpose: "Reports interpretive, non-numerical research"),
            DocumentType(slug: "clinical-trial-report", name: "Clinical Trial Report", purpose: "Documents phases and outcomes of a clinical trial"),
            DocumentType(slug: "grant-proposal", name: "Grant Proposal", purpose: "Request for funding to support research"),
            DocumentType(slug: "research-protocol", name: "Research Protocol", purpose: "Detailed plan for conducting research"),
            DocumentType(slug: "irb-application", name: "IRB Application", purpose: "Institutional Review Board ethics approval"),
            DocumentType(slug: "data-collection-instrument", name: "Data Collection Instrument", purpose: "Survey, questionnaire, or interview protocol"),
            DocumentType(slug: "data-analysis-report", name: "Data Analysis Report", purpose: "Documents data processing and findings"),
            DocumentType(slug: "technical-report", name: "Technical Report", purpose: "In-depth report on a technical investigation"),
            DocumentType(slug: "conference-paper", name: "Conference Paper", purpose: "Scholarly paper presented at a conference"),
            DocumentType(slug: "conference-poster", name: "Conference Poster", purpose: "Visual research summary for conferences"),
            DocumentType(slug: "preprint", name: "Preprint", purpose: "Non-peer-reviewed early research draft"),
            DocumentType(slug: "patent-application", name: "Patent Application", purpose: "Invention protection filing"),
            DocumentType(slug: "patent-specification", name: "Patent Specification", purpose: "Detailed written description of an invention"),
            DocumentType(slug: "scientific-correspondence-letter", name: "Scientific Correspondence / Letter", purpose: "Brief communication in a journal"),
            DocumentType(slug: "correction-notice", name: "Correction Notice", purpose: "Errata notice for a published article"),
            DocumentType(slug: "book-review", name: "Book Review (Academic)", purpose: "Evaluation of a scholarly publication"),
            DocumentType(slug: "data-notes", name: "Data Notes", purpose: "Documentation accompanying a dataset"),
            DocumentType(slug: "methods-article", name: "Methods Article", purpose: "Describes a novel scientific method"),
            DocumentType(slug: "clinical-case-report", name: "Clinical Case Report", purpose: "Documents a unique patient case for the medical community"),
        ]),
        Category(slug: "marketing-sales-communications-documents", name: "Marketing, Sales & Communications Documents", types: [
            DocumentType(slug: "marketing-plan", name: "Marketing Plan", purpose: "Strategic roadmap for marketing activities"),
            DocumentType(slug: "content-calendar", name: "Content Calendar", purpose: "Schedule of marketing content to be published"),
            DocumentType(slug: "press-release", name: "Press Release", purpose: "Official announcement to media outlets"),
            DocumentType(slug: "media-kit", name: "Media Kit", purpose: "Package of company information for press"),
            DocumentType(slug: "brochure", name: "Brochure", purpose: "Printed or digital promotional summary"),
            DocumentType(slug: "flyer-pamphlet", name: "Flyer / Pamphlet", purpose: "Brief promotional or informational handout"),
            DocumentType(slug: "whitepaper", name: "Whitepaper (Marketing)", purpose: "In-depth report used as a lead generation tool"),
            DocumentType(slug: "case-study-marketing", name: "Case Study (Marketing)", purpose: "Client success story for promotional purposes"),
            DocumentType(slug: "product-sheet-data-sheet", name: "Product Sheet / Data Sheet", purpose: "Specifications of a product or service"),
            DocumentType(slug: "catalog", name: "Catalog", purpose: "Comprehensive listing of products or services"),
            DocumentType(slug: "proposal", name: "Proposal (Sales)", purpose: "Customized offer submitted to a prospect"),
            DocumentType(slug: "sales-report", name: "Sales Report", purpose: "Summary of sales performance and pipeline"),
            DocumentType(slug: "customer-survey", name: "Customer Survey", purpose: "Gathers customer feedback and satisfaction data"),
            DocumentType(slug: "testimonial", name: "Testimonial", purpose: "Customer endorsement of a product or service"),
            DocumentType(slug: "social-media-policy", name: "Social Media Policy", purpose: "Guidelines for employee social media conduct"),
            DocumentType(slug: "brand-style-guide", name: "Brand Style Guide", purpose: "Rules for consistent brand representation"),
            DocumentType(slug: "newsletter", name: "Newsletter", purpose: "Periodic communication to subscribers"),
            DocumentType(slug: "email-campaign", name: "Email Campaign", purpose: "Targeted digital marketing message"),
            DocumentType(slug: "landing-page-copy", name: "Landing Page Copy", purpose: "Web content designed to convert visitors"),
            DocumentType(slug: "advertising-contract", name: "Advertising Contract", purpose: "Agreement for placement of advertising"),
        ]),
        Category(slug: "financial-securities-investment-documents", name: "Financial Securities & Investment Documents", types: [
            DocumentType(slug: "prospectus", name: "Prospectus", purpose: "Official investment offering document"),
            DocumentType(slug: "private-placement-memorandum", name: "Private Placement Memorandum (PPM)", purpose: "Unregistered securities offering disclosure"),
            DocumentType(slug: "investment-policy-statement", name: "Investment Policy Statement", purpose: "Defines investment objectives and constraints"),
            DocumentType(slug: "brokerage-account-agreement", name: "Brokerage Account Agreement", purpose: "Terms for a securities trading account"),
            DocumentType(slug: "stock-certificate", name: "Stock Certificate", purpose: "Evidence of share ownership"),
            DocumentType(slug: "bond-indenture", name: "Bond Indenture", purpose: "Contract governing bond terms"),
            DocumentType(slug: "debenture", name: "Debenture", purpose: "Unsecured debt instrument document"),
            DocumentType(slug: "sec-form-10-k", name: "SEC Form 10-K", purpose: "Annual report filed with the SEC"),
            DocumentType(slug: "sec-form-10-q", name: "SEC Form 10-Q", purpose: "Quarterly report filed with the SEC"),
            DocumentType(slug: "sec-form-8-k", name: "SEC Form 8-K", purpose: "Current report on material events (SEC)"),
            DocumentType(slug: "sec-form-s-1", name: "SEC Form S-1", purpose: "Initial public offering registration statement"),
            DocumentType(slug: "form-def-14a", name: "Form DEF 14A (Proxy Statement)", purpose: "Discloses voting matters for shareholder meetings"),
            DocumentType(slug: "financial-model", name: "Financial Model", purpose: "Quantitative projection tool (spreadsheet-based)"),
            DocumentType(slug: "term-sheet", name: "Term Sheet", purpose: "Non-binding investment deal summary"),
            DocumentType(slug: "cap-table", name: "Cap Table", purpose: "Equity ownership structure of a company"),
            DocumentType(slug: "portfolio-statement", name: "Portfolio Statement", purpose: "Summary of investment holdings"),
            DocumentType(slug: "trade-confirmation", name: "Trade Confirmation", purpose: "Record of a completed securities trade"),
            DocumentType(slug: "escrow-agreement", name: "Escrow Agreement", purpose: "Third-party fund holding arrangement"),
            DocumentType(slug: "convertible-note", name: "Convertible Note", purpose: "Debt that converts to equity under defined terms"),
            DocumentType(slug: "safe-agreement", name: "SAFE Agreement", purpose: "Simple Agreement for Future Equity (startup funding)"),
        ]),
        Category(slug: "nonprofit-governance-compliance-documents", name: "Nonprofit, Governance & Compliance Documents", types: [
            DocumentType(slug: "irs-form-990", name: "IRS Form 990", purpose: "Annual financial filing for nonprofits"),
            DocumentType(slug: "501-application", name: "501(c)(3) Application (Form 1023)", purpose: "Application for nonprofit tax exemption"),
            DocumentType(slug: "donor-acknowledgment-letter", name: "Donor Acknowledgment Letter", purpose: "Tax receipt for charitable contribution"),
            DocumentType(slug: "grant-agreement", name: "Grant Agreement", purpose: "Terms and conditions for a grant award"),
            DocumentType(slug: "memorandum-of-agreement", name: "Memorandum of Agreement (MOA)", purpose: "Binding agreement between organizations"),
            DocumentType(slug: "code-of-ethics", name: "Code of Ethics", purpose: "Organizational ethical guidelines"),
            DocumentType(slug: "conflict-of-interest-policy", name: "Conflict of Interest Policy", purpose: "Disclosure and management of conflicts"),
            DocumentType(slug: "whistleblower-policy", name: "Whistleblower Policy", purpose: "Protections for reporting misconduct"),
            DocumentType(slug: "board-governance-policy", name: "Board Governance Policy", purpose: "Rules for board operations and responsibilities"),
            DocumentType(slug: "compliance-manual", name: "Compliance Manual", purpose: "Guide to regulatory requirements"),
            DocumentType(slug: "risk-assessment", name: "Risk Assessment", purpose: "Identifies and evaluates organizational risks"),
            DocumentType(slug: "internal-controls-documentation", name: "Internal Controls Documentation", purpose: "Describes controls to prevent financial misstatement"),
            DocumentType(slug: "sox-compliance-document", name: "SOX Compliance Document", purpose: "Sarbanes-Oxley Act compliance evidence"),
            DocumentType(slug: "aml-policy", name: "AML Policy", purpose: "Anti-money laundering policy"),
            DocumentType(slug: "kyc-documentation", name: "KYC Documentation", purpose: "Know Your Customer identity verification records"),
            DocumentType(slug: "regulatory-filing", name: "Regulatory Filing (Industry-Specific)", purpose: "Submissions to sector regulators (e.g., FDA, FCC)"),
            DocumentType(slug: "environmental-compliance-report", name: "Environmental Compliance Report", purpose: "Documents adherence to environmental laws"),
            DocumentType(slug: "accreditation-report", name: "Accreditation Report", purpose: "Documents adherence to industry standards"),
            DocumentType(slug: "policy-memo", name: "Policy Memo", purpose: "Internal guidance on a policy matter"),
            DocumentType(slug: "standard-operating-procedure", name: "Standard Operating Procedure (SOP)", purpose: "Detailed instructions for a recurring task"),
        ]),
        Category(slug: "diplomatic-military-intelligence-documents", name: "Diplomatic, Military & Intelligence Documents", types: [
            DocumentType(slug: "diplomatic-note", name: "Diplomatic Note", purpose: "Formal written communication between governments"),
            DocumentType(slug: "note-verbale", name: "Note Verbale", purpose: "Semi-formal diplomatic communication"),
            DocumentType(slug: "d-marche", name: "Démarche", purpose: "Formal diplomatic representation or protest"),
            DocumentType(slug: "diplomatic-cable-telegram", name: "Diplomatic Cable / Telegram", purpose: "Classified inter-governmental communication"),
            DocumentType(slug: "extradition-treaty", name: "Extradition Treaty", purpose: "Agreement for criminal suspect transfer between countries"),
            DocumentType(slug: "status-of-forces-agreement", name: "Status of Forces Agreement (SOFA)", purpose: "Governs foreign military presence in a country"),
            DocumentType(slug: "security-clearance-document", name: "Security Clearance Document", purpose: "Authorization to access classified information"),
            DocumentType(slug: "intelligence-report", name: "Intelligence Report", purpose: "Classified analysis of security-relevant information"),
            DocumentType(slug: "military-order", name: "Military Order", purpose: "Directive issued within a military chain of command"),
            DocumentType(slug: "after-action-report", name: "After-Action Report (AAR)", purpose: "Post-mission or post-event analysis"),
            DocumentType(slug: "rules-of-engagement-document", name: "Rules of Engagement Document", purpose: "Guidelines governing military force use"),
            DocumentType(slug: "war-diary", name: "War Diary", purpose: "Official log of military unit activities"),
            DocumentType(slug: "field-manual", name: "Field Manual", purpose: "Operational doctrine and tactics guide"),
            DocumentType(slug: "defense-contract", name: "Defense Contract", purpose: "Procurement agreement for military goods/services"),
            DocumentType(slug: "veterans-benefits-application", name: "Veterans' Benefits Application", purpose: "Claim for government benefits by military veterans"),
        ]),
        Category(slug: "specialized-miscellaneous-document-types", name: "Specialized & Miscellaneous Document Types", types: [
            DocumentType(slug: "screenplay", name: "Screenplay", purpose: "Script for a film or television production"),
            DocumentType(slug: "storyboard", name: "Storyboard", purpose: "Visual narrative planning document"),
            DocumentType(slug: "creative-brief", name: "Creative Brief", purpose: "Outlines goals for a creative project"),
            DocumentType(slug: "copyright-registration", name: "Copyright Registration", purpose: "Records ownership of creative work"),
            DocumentType(slug: "trademark-application", name: "Trademark Application", purpose: "Registers a brand mark with government"),
            DocumentType(slug: "trade-secret-policy", name: "Trade Secret Policy", purpose: "Documents procedures to protect proprietary info"),
            DocumentType(slug: "franchise-disclosure-document", name: "Franchise Disclosure Document (FDD)", purpose: "Required disclosure before franchise sale"),
            DocumentType(slug: "deed-of-gift", name: "Deed of Gift", purpose: "Transfers ownership of donated property"),
            DocumentType(slug: "certificate-of-authenticity", name: "Certificate of Authenticity", purpose: "Verifies an item is genuine"),
            DocumentType(slug: "appraisal-certificate", name: "Appraisal Certificate", purpose: "Professional valuation statement"),
            DocumentType(slug: "religious-decree-fatwa", name: "Religious Decree / Fatwa", purpose: "Authoritative religious legal ruling"),
            DocumentType(slug: "church-constitution", name: "Church Constitution", purpose: "Governing document for a religious organization"),
            DocumentType(slug: "baptism-confirmation-register", name: "Baptism / Confirmation Register", purpose: "Church record of religious rites"),
            DocumentType(slug: "archival-finding-aid", name: "Archival Finding Aid", purpose: "Guide to contents of an archival collection"),
            DocumentType(slug: "chain-of-custody-document", name: "Chain of Custody Document", purpose: "Tracks evidence handling in legal/scientific context"),
            DocumentType(slug: "environmental-report", name: "Environmental Report", purpose: "Assessment of environmental conditions on a site"),
            DocumentType(slug: "sustainability-report", name: "Sustainability Report", purpose: "Documents an organization's environmental impact"),
            DocumentType(slug: "carbon-credit-certificate", name: "Carbon Credit Certificate", purpose: "Evidence of verified carbon offset"),
            DocumentType(slug: "safety-data-sheet", name: "Safety Data Sheet (SDS / MSDS)", purpose: "Hazardous material handling information"),
            DocumentType(slug: "food-safety-record", name: "Food Safety Record", purpose: "Documents food handling and temperature compliance"),
            DocumentType(slug: "agricultural-certificate", name: "Agricultural Certificate", purpose: "Certifies crops or livestock meet regulations"),
            DocumentType(slug: "notarial-certificate", name: "Notarial Certificate", purpose: "Notary's formal certification"),
            DocumentType(slug: "apostille", name: "Apostille", purpose: "International document authentication certificate"),
            DocumentType(slug: "letter-rogatory", name: "Letter Rogatory", purpose: "Formal court request to a foreign authority"),
            DocumentType(slug: "legislative-history-document", name: "Legislative History Document", purpose: "Background materials accompanying a law's passage"),
            DocumentType(slug: "parliamentary-record", name: "Parliamentary Record (Hansard)", purpose: "Official verbatim legislative debate record"),
            DocumentType(slug: "sports-contract", name: "Sports Contract", purpose: "Professional athlete employment agreement"),
            DocumentType(slug: "entertainment-contract", name: "Entertainment Contract", purpose: "Agreement for creative performance or production"),
            DocumentType(slug: "talent-release-form", name: "Talent Release Form", purpose: "Permission to use a person's likeness"),
            DocumentType(slug: "model-release", name: "Model Release", purpose: "Grants right to publish a model's image"),
            DocumentType(slug: "photo-license", name: "Photo License", purpose: "Rights to use a photograph commercially"),
            DocumentType(slug: "broadcast-license", name: "Broadcast License", purpose: "Government authorization to operate a station"),
            DocumentType(slug: "construction-contract", name: "Construction Contract", purpose: "Agreement for building or renovation work"),
            DocumentType(slug: "lien-waiver", name: "Lien Waiver", purpose: "Releases a contractor's lien rights after payment"),
            DocumentType(slug: "punch-list", name: "Punch List", purpose: "Final deficiency list before project closeout"),
            DocumentType(slug: "commissioning-report", name: "Commissioning Report", purpose: "Verifies a new system is installed and operational"),
            DocumentType(slug: "utility-agreement", name: "Utility Agreement", purpose: "Contract for utility service provision"),
            DocumentType(slug: "demand-letter", name: "Demand Letter", purpose: "Formal pre-litigation demand for action"),
            DocumentType(slug: "letter-of-transmittal", name: "Letter of Transmittal", purpose: "Accompanies documents being formally submitted"),
            DocumentType(slug: "memorandum", name: "Memorandum (Internal Memo)", purpose: "Brief formal internal communication"),
        ]),
    ]

    /// Flat list of every type across all categories (500 items).
    static var allTypes: [DocumentType] {
        categories.flatMap { $0.types }
    }

    /// All type slugs joined by commas, suitable for inclusion in an LLM prompt.
    static var allTypeSlugs: [String] {
        allTypes.map { $0.slug }
    }

    /// All category slugs joined by commas, suitable for inclusion in an LLM prompt.
    static var allCategorySlugs: [String] {
        categories.map { $0.slug }
    }

    /// Look up a category by slug (case-insensitive).
    static func category(forSlug slug: String) -> Category? {
        let s = slug.lowercased()
        return categories.first { $0.slug == s }
    }

    /// Look up a document type by slug (case-insensitive). Searches across all categories.
    static func type(forSlug slug: String) -> DocumentType? {
        let s = slug.lowercased()
        return allTypes.first { $0.slug == s }
    }

    /// Find the parent category for a given type slug.
    static func category(containingTypeSlug slug: String) -> Category? {
        let s = slug.lowercased()
        return categories.first { c in c.types.contains(where: { $0.slug == s }) }
    }
}